### ISSUE TITLE
Série: recherche dans sous-répertoires du torrent

### ISSUE THREAD

**Issue by Gregsr** [rik91/script.quasar.t411-rik91#1]
Bonjour Eric,

Tout d'abord, merci d'avoir réalisé ce provider que j'utilise quasi tous les jours depuis 2 mois.

J'ai remarqué que, lors d'une recherche d'un épisode d'une série, la recherche ne s'étendait pas aux sous-répertoires de torrents.
Je m'explique avec un exemple: pour Macgyver S01E01, il ne trouvera pas cet épisode dans le torrent "MacGyver iNTEGRALE MULTi DVDRiP x264-LecatTeam".
Le provider t411 de Torrenter V2 permet "d'explorer" ce genre de sous-répertoires et de télécharger uniquement le fichier voulu si ça peut t'aider.

Merci,

Gregsr

**Comment by rik91** [comment]
Salut Gregsr,

Content que mon provider te soit utile. :-)

J'ai regardé en détail le code du provider de Torrenter V2.
En fait, que le torrent "MacGyver iNTEGRALE MULTi DVDRiP x264-LecatTeam" ressorte est un peu un hasard...

Je m'explique, pour faire sa requête dans T411, il utilise cette url : 
http://www.t411.ch/torrents/search/?search=Macgyver+S01E01&order=seeders&type=desc 
A partir de se résultat, il extrait tous les torrents "Approuvés par la communauté" (ceux avec un **(A)**) pour les proposer dans l'interface de Torrenter.

Si tu fais la même recherche dans Torrenter mais cette fois ci pour "Macgyver S01E0**2**", tu verra qu'il ressort les mêmes résultats que pour la recherche "Macgyver S01E0**1**" alors que pourtant il existe bien un torrent "MacGyver.s01e02.MULTI.DVDRip.X264.576P.AC3-carpediem" mais lui n'est pas approuvé.

Bref, son système n'est pas complètement au point car si tous les épisodes étaient approuvés, ils ressortiraient tous à chaque fois. :-\

Contrairement à lui, pour faire mes recherches dans t411 : 
1. J'utlise l'API de t411 et non pas le site.(http://api.t411.ch/)
2. Je ne recherche pas les épisodes de cette manière (S0XE0X), j'utilise les listes déroulantes proposées par le site car les recherches S0XE0X ne donne plus rien de bien depuis quelque temps.
Ce qui correspond à une recherche de ce type (mais moi je l'a fait à travers l'API) :
http://www.t411.ch/torrents/search/?name=Macgyver&description=&file=&user=&cat=210&subcat=433&term%5B46%5D%5B%5D=937&term%5B45%5D%5B%5D=968&search=%40name+Macgyver+&submit=Recherche
D’où le fait que je ne renvoi qu'un résultat et avec ma technique une recherche de l'épisode 2 fonctionne contrairement à Torrenter.

Ensuite, si j'arrivai à renvoyer le torrent "MacGyver iNTEGRALE MULTi DVDRiP x264-LecatTeam", il faudrait que Quasar puisse afficher les fichiers disponibles dans ce torrent comme le fait Torrenter. Mais pour le moment il ne me semble pas qu'il en soit capable.

Par contre, dans Quasar, il y a un système pour recherche des saisons complètes.
Quand tu es sur la liste des saisons, tu cliques droit sur la saison désirée et là il y a un menu "Choisir un flux".
Là je renvoi les torrents par saison complète et normalement Quasar utilise ensuite ce torrent pour chaque épisode de la saison.
Je t'avouerais que je n'ai jamais vraiment essayé ce système, je te laisse le soin de tester toi même.

En espérant avoir répondu à ta question...
Bon Streaming

Eric

**Comment by Gregsr** [comment]
Merci pour ces éclaircissements ;)
"Choisir un flux" via la liste des saisons fonctionne.
