### ISSUE TITLE
Error during a research

### ISSUE THREAD

**Issue by Gregsr** [rik91/script.quasar.t411-rik91#11]
Script doesn't work (on MINIX NEO-U1 with Android 5.1.1; KODI 17.1 for Android ARM 32-bit): error during a research
This is log file https://pastebin.com/raw/4kHPRVE5

**Comment by rik91** [comment]
En effet, il semblerait que l'api de t411 que j'utilise dans le provider ne soit plus disponible...
C'est peut être un problème temporaire ? En tout cas sur le site ils n'annoncent pas la fermeture de celle ci.
Adresse de l'API : http://api.t411.ai

**Comment by Gregsr** [comment]
En effet http://irc.t411.ai/screens/ms/tutoriels/Nathann83/ip_t411.php

**Comment by Gregsr** [comment]
L'API est ONLINE mais toujours une erreur lors de la recherche
https://pastebin.com/raw/azysh5YJ

**Comment by lanzorg** [comment]
Cela semble fonctionné avec le script de paco112.  
https://github.com/Paco112/script.quasar.t411

Sinon il y a Burst, mais les résultats sont catastrophiques !

**Comment by rik91** [comment]
Salut tout le monde,
En fait il suffit de passer l'url de l'api dans les paramètres en https pour que cela fonctionne.

**Comment by rik91** [comment]
Personne pour confirmer que ça fonctionne ?

**Comment by Gregsr** [comment]
Je n'ai pas encore eu l'occasion. Je teste ce soir

**Comment by lanzorg** [comment]
L'équipe du site travaille de manière intensive sur les serveurs et hélas il est toujours impossible de télécharger quoi que ce soit. Pour le moment le scraping fonctionne bien, mais j'attendrai encore deux ou trois jours avant de clôturer cette issue.

**Comment by Gregsr** [comment]
Plus d'erreur lors d'une recherche

**Comment by Gregsr** [comment]
Serait-il possible de renvoyer les différents tops (100, today, week, month) en faisant une recherche générale sur, par exemple, "top 100", "top today"... (je n'ai pas trouvé la section pour faire ce genre de demande) ?

**Comment by rik91** [comment]
Tu devrais ouvrir une issue à part que je transformerais en "enhancement" (amélioration)
Mais là c'est pas vraiment en rapport avec le l'issue en cours !
