### ISSUE TITLE
Lister top 100, top today...

### ISSUE THREAD

**Issue by Gregsr** [rik91/script.quasar.t411-rik91#12]
Serait-il possible de renvoyer les différents tops (100, today, week, month) en faisant une recherche générale sur, par exemple, "top 100", "top today"... ?

**Comment by rik91** [comment]
A ton avis, faudrait il que ça conserve les paramètres de filtrage ? Genre si on a dit qu'on ne veut pas les 3D, ça les renvois pas les 3D des tops ?

**Comment by Gregsr** [comment]
Je pense que ce serait mieux de les conserver.
Est-ce qu'il serait possible d'afficher uniquement les films apparaissant dans les tops? Même chose pour les séries? Genre "top 100 films", "top 100 series"...
