### ISSUE TITLE
Séries Tv: lister les résultats saisons complètes ET les épisodes seuls ? 

### ISSUE THREAD

**Issue by Maumtiesse** [rik91/script.quasar.t411-rik91#14]
Bonjour rik91.
1) Merci et super boulot, ton script marche super bien.
2) Est-il possible lors de la recherche de fournir aussi bien les épisodes pour les séries que les packs de saisons complètes. Actuellement c'est l'un ou l'autre. Exemple pour les séries plus anciennes, le script ne trouve pas les épisodes seuls, et donc résultat = 0 source. Il me faut alors aller dans les options et changer pour rechercher les saisons packs. Dans ce cas il trouve des sources. Inversement c'est pareil... 
Je pense que ce serait cool d'avoir l'option "chercher également les packs saisons"
Merci.

**Comment by rik91** [comment]
Bonjour Maumtiesse,

Dans Quasar, il y a un système pour recherche des saisons complètes sans avoir à modifier le paramétrage dans le provider.
Quand tu es sur la liste des saisons, tu cliques droit sur la saison désirée et là il y a un menu "Choisir un flux".
Là je renvoi les torrents par saison complète.

Déjà dans un premier temps ça te feras gagner quelques manipulations...

**Comment by lanzorg** [comment]
Pas bête comme feature surtout pour les petits nouveaux.
J'ai tellement l'habitude de chercher par saison.

**Comment by Maumtiesse** [comment]
En effet. Ça fonctionne vraiment très très bien!
Encore merci.
