### ISSUE TITLE
T411.li

### ISSUE THREAD

**Issue by bubuleur** [rik91/script.quasar.t411-rik91#2]
Bonjour,
je viens vers vous pour vous dire que T411 a déménagé de lieu maintenant c'est  T411.li 
faut il changer juste l'adresse dans les paramètres de votre soft ?
En vous remerciant

**Comment by rik91** [comment]
Bonjour bubuleur,

Merci pour l'info, je viens de publier une version 1.3.6b avec la nouvelle URL.
Mais en effet, tu peux modifier l'URL directement dans les paramètres du pluggin.

Rik91
