### ISSUE TITLE
Re

### ISSUE THREAD

**Issue by bubuleur** [rik91/script.quasar.t411-rik91#3]
Re
Merci pour votre réactivité pour le changement d'adresse
J'ai mise a jour mais pourquoi dans les paramétres du providers cela reste sur api.t411.ch ca devrais etre en .li ?
Cordialement
Merci

**Comment by rik91** [comment]
Oui malheureusement, le système de plugin de Kodi n'est pas parfait et si je fait une mise à jour dans le fichier des paramètres, il n'est pas répercuté lors de la mise à jour car il conserve l'ancien fichier au cas ou tu aurais fait des personnalisations.
Ou bien si il y a une technique pour le faire, je ne la connais pas...

**Comment by bubuleur** [comment]
Bonjour ah ok d'accord je ne savais pas
J'utilise Quasar et vos providers avec un raspberry pi 3 donc il faudrait que je formate ma microsd et que je remette un kodi tout neuf pour que l'adressse api.t411.ch change en .li
Merci pour le changement pour cpasbien 
Ps: je me sers souvent de vos provider c'est genial tres bon boulot que vous avez fait 
Merci encore
Cordialement

**Comment by rik91** [comment]
Bonjour,
Content que mes providers servent à quelqu'un ! ;-)
Pourquoi reformater votre microsd, non il vous faut juste changer l'url dans les paramètre du provider. 
Quand vous faites ça ça ne fonctionne toujours pas ?
Je viens de déménager alors je vous avoue que j'ai pas encore tout rebrancher chez moi et que du coup en ce moment je me sert pas énormément de Quasar.
Je vais essayer de le retester aujourd'hui.
Rik91

**Comment by bubuleur** [comment]
Ah d'accord je croyais qu'il fallait formater le tout sinon je vous dit ça se soir pour voir si ça marche en mettant .li
Merci

**Comment by rik91** [comment]
Je viens de tester, en mettant le .li, ça fonctionne.
Si vous n'avez pas de résultat ou rarement, essayez d'augmenter un peu le "Délai d'attente max (secondes)" dans les paramètres de Quasar -> Onglet Providers -> Delai d'attente maximum du Provider personnalisé.
Il faut faire "Activé (risqué)" et passé le "Délai d'attente max (secondes)" à 10 au lieu de 4 secondes.
Rik91

**Comment by bubuleur** [comment]
ok je ne savais pas pour le parametres de quasar je regarde ce soir merci

**Comment by bubuleur** [comment]
Ok c'est bon ça marche merci pour vos renseignements
