### ISSUE TITLE
t411 gives error

### ISSUE THREAD

**Issue by lyanko** [rik91/script.quasar.t411-rik91#5]
Nevermind. :)

**Comment by rik91** [comment]
;-)

**Comment by lyanko** [comment]
In fact there is the problem xD 

Torrent won't start download on Quasar. I changed domain in provider settings to .li and search works fine but reproducing failes.  I don't know where is the problem, maybe t411 api has changed?

**Comment by nonopubli** [comment]
Bonjour. J'ai a priori le même problème, non résolu. Cpasbien fonctionne, mais pas T411. Quasar propose bien des liens, le téléchargement démarre, mais il reste à zéro et il affiche une URL (http://API.t411.li/download...) au lieu du nom du torrent.
J'ai pourtant tout réinstallé et réparée été.
Une idée ?
Merci

**Comment by rik91** [comment]
Il semblerait que ça fonctionne plus depuis que Quasar gère les private tracker.
Je vais regarder ça !

It seems that it doesn't works since Quasar support private tracker.
I'll look at that!

**Comment by rik91** [comment]
J'ai sortie une nouvelle version, testez et dites moi !

I push a new version. Test and say me

**Comment by nonopubli** [comment]
Trop fort !!!!!
Merci beaucoup pour cette réactivité. Cela semble fonctionner à merveille.
Bonnes fêtes et bonne continuation, vos plugins sont top !!

**Comment by lyanko** [comment]
I get update t411 1.3.5 version but for me it's still the same. Provider stuck on finding.

I make log file http://paste.ubuntu.com/23689103/

**Comment by rik91** [comment]
You have to download 1.3.7 version here 👍  https://github.com/rik91/script.quasar.t411-rik91/releases/tag/1.3.7

Unfortunately the repositories are no longer truly up to date.

**Comment by rik91** [comment]
@monopubli Merci ! Bonne fête à vous aussi et je suis heureux que mes providers vous soit utile.

**Comment by lyanko** [comment]
Magnificent +1

Everything works great now.

**Comment by rik91** [comment]
@nonopubli Pour info j'ai codé une provider pour le site www.torrent9.biz.
Je ne sais pas si vous avez remarqué mais il n'y a plus de nouveau ajout sur cpasbien depuis quelque temps. Le site va mourir je pense et c'est torrent9 le remplaçant, celui ci contient tout ce que contenait cpasbien plus des nouveaux ajouts réguliers.
On voit bien sur cpasbien que dans les top films, la majorité des liens renvoi vers torrent9...

**Comment by nonopubli** [comment]
Bonjour,
Merci pour tout ce travail !!
J'ai testé le plugin Torrent9 mais il plante chez moi...
Je vous envoie asap le libellé de l'erreur, si j'ai le temps de le lire !
Merci

**Comment by rik91** [comment]
J'ai rééssayer le provider et ça fonctionne bien chez moi !
