### ISSUE TITLE
request if it's not a problem

### ISSUE THREAD

**Issue by lyanko** [rik91/script.quasar.t411-rik91#6]
Hi I'm using your t411 and UHDBits provider without a problem and it's amazing. I wonder could you make one or two more providers for private trackers? Since yesterday Quasar supports private trackers so now that isn't problem anymore :)

I can give you user and pass for some if you don't have. I can give you credentials for rutracker and hd-space. It's not urgent of course, when you have free time.

**Comment by lyanko** [comment]
actually I can give invite for hd-space :)

**Comment by rik91** [comment]
At the time I write it is impossible for me to connect to the site

**Comment by lyanko** [comment]
https://hd-space.org/index.php?page=signup
And this?

Don't know why is site hard to connect. Didn't have problem with that for hd-space? Only when they are doing some maintenance but now everything seems fine.

Ok, nothing then. If it doesn't work let it go. Thanks for Uhdbits and t411 anyway +1

**Comment by rik91** [comment]
The site is OK now.
I will see if it's feasible.

**Comment by rik91** [comment]
HDSpace is an horrible site, the HTML of the page is not valid and the parser can not extract the info from the page. I try a lot of things but no result.
This site has been coded with feet...
Sorry

**Comment by lyanko** [comment]
No problem mate and thanks for tryin anyway. ;) Also sorry for a bit disturbance, I had best intetions, now when Quasar starts to play private torrents I wanted to have more providers for those but damn it if is site coded badly like that I will just forget about him hahaha. 

Did you have plans for maybe some another providers with private torrents in future cause your uhdbits and t411 works trully great? I'm using yours for those two sites and mancuniancol's for some others. It's great combination :)

**Comment by rik91** [comment]
When I login, I'm redirect to Google. it's normal ?

**Comment by lyanko** [comment]
maybe cause I need to logout first xD

**Comment by rik91** [comment]
ah ok ! You are caramelo on the tvaddons forum ?

**Comment by lyanko** [comment]
yes yes :) 

I'm active there

**Comment by rik91** [comment]
always redirect to Google !
Can be because I am in France ?

**Comment by lyanko** [comment]
I find why is that happening. 

"Partis.si is now enabled for free sign up and after you create your account you shouldn't login directly as it will redirect you to Google,instead you should take password recovery and then just use your old password." - from this review up

Don't know why is this asked but I will try my pass recovery

**Comment by rik91** [comment]
Yes I have seen that, it's because I send you the link too.
It's not an IP problem ?

**Comment by lyanko** [comment]
Don't know why they wanna ban France IP's honestly. 

I asked for pass recovery and they showed me some picture hamster and something on Slovenian which I don't understaind xD But try now, maybe now it will?

**Comment by rik91** [comment]
No always redirect.
Maybe I have to do the password recovery for they save my IP associated to the account

**Comment by lyanko** [comment]
No I find solution.

Register account.
Recover password (when they sent you the e-mail with recovery link, click the link and automatically login.)
Bookmark the page and start using this awesome tracker.
Enjoy. :)

But for now they didn't send me any link on mail. I will wait for that ;)

**Comment by lyanko** [comment]
Rik bro please you can close this as Partis won't give permission to any IP except Slovenian, Serbian and Croatian. They are stupid but that is how it is :(

And they are tons of other good trackers out there who don't have those stupid limitations so it's not big deal.

**Comment by lyanko** [comment]
Rik I think I finally found some working great tv show tracker. xD 
It's called Freshon.Tv and it's Romanian only for tv shows.

https://freshon.tv/login.php?returnto=%2F

User: tozanervoza
Password: *0gb10asape

So when you have time and will please check it. It's great place for tv shows. Just it would be nice to have also option like t411 or uhdbits providers to choose what to open single episodes or season packs? In my opinion tracker is a lot better for season packs cause there are plenty.

**Comment by lyanko** [comment]
Rik I think I finally found tracker who will work xD It's **Freshon.Tv** and it's only for tv shows. I will give you link for log in and user and pass so when you want, when you have time or will please check if can you make provider for it. :)

https://freshon.tv/login.php?returnto=%2F

User: tozanervoza
Password: *0gb10asape
