### ISSUE TITLE
Le téléchargement démarre mais reste à 0

### ISSUE THREAD

**Issue by nonopubli** [rik91/script.quasar.t411-rik91#7]
Bonjour.
Merci pour votre super travail !!
J'ai un problème sous Quasar/Xbian.
Cpasbien fonctionne, mais pas T411. Quasar propose bien des liens, le téléchargement démarre, mais il reste à zéro et il affiche une URL (http://api.t411.li/torrents/download/...) au lieu du nom du torrent, et :0, U:0, S:0/-1 P:0/-1.
J'ai pourtant tout réinstallé et reparamétré.
Une idée ?
Merci

**Comment by rik91** [comment]
Same issue as #5
